"""ROM registry + path resolvers for integration tests.

Pulled out of `tests/integration/conftest.py` so unit tests under
`tests/unit/integration/` can import these as a real module rather than
reaching into private conftest symbols.
"""
from __future__ import annotations

from pathlib import Path

import yaml

PROJECT_ROOT = Path(__file__).resolve().parents[2]

LOVE_YOURSELF_ROM_NAME = "Love Yourself.smc"
LOVE_YOURSELF_GAME_ID = "bd94dbb29012c7f5"

TOOTHPASTE_ROM_NAME = "Toothpaste.smc"
CLEAN_SMW_ROM_NAME = "_clean.smc"

# rom_key -> filename in config.yaml's rom.dir.
# Each entry produces one cached session-scoped RAHarness in `ra_harness_factory`.
# Tests must declare which ROM they need via the matching named fixture
# (e.g. `ra_harness_vanilla_smw`); there is no implicit `default` fallback.
#
# Adding a new ROM requires THREE things:
#   1. A `<rom_key>: "<rom_filename>"` line below.
#   2. A fresh-boot savestate at tests/integration/states/<rom_basename>.state,
#      generated via `python scripts/make_fresh_boot_state.py --rom-key <key>`.
#      Without it, RAPokeEngine can't reset between scenarios and tests share
#      ROM CPU/SPC state across runs (project_transition_state_leak).
#   3. A `ra_harness_<rom_key>` fixture in conftest.py that calls
#      `ra_harness_factory("<key>")`. Tests reference fixtures by name.
ROM_REGISTRY: dict[str, str] = {
    "vanilla_smw": CLEAN_SMW_ROM_NAME,
    "love_yourself": LOVE_YOURSELF_ROM_NAME,
    "toothpaste": TOOTHPASTE_ROM_NAME,
}

# Per-ROM "fresh boot" savestate. Generated by `scripts/make_fresh_boot_state.py`
# and committed under tests/integration/states/. Loaded by RAPokeEngine before
# every scenario so the session-scoped harness doesn't leak SPC700/CPU state
# between transition scenarios.
INTEGRATION_STATES_DIR = Path(__file__).resolve().parent / "states"


def load_config() -> dict:
    """Load config.yaml from project root."""
    config_path = PROJECT_ROOT / "config.yaml"
    if config_path.exists():
        with open(config_path) as f:
            return yaml.safe_load(f)
    return {}


def state_path_for(rom_filename: str) -> Path | None:
    """Resolve the fresh-boot savestate for `rom_filename` if one is committed.

    Returns None when no .state file exists — the harness treats this as
    "skip the per-scenario boot reset" so a new ROM works at session-scope
    until make_fresh_boot_state.py is run for it.
    """
    candidate = INTEGRATION_STATES_DIR / f"{Path(rom_filename).stem}.state"
    return candidate if candidate.exists() else None


def resolve_rom_path(rom_key: str) -> Path:
    """Resolve a registered rom_key to an absolute Path under config.yaml's rom.dir.

    Hard-fails (RuntimeError) on unknown key, missing rom.dir, or missing file.
    Per CLAUDE.md, hard-fail rather than pytest.skip so missing infra surfaces
    as a red test.
    """
    if rom_key not in ROM_REGISTRY:
        raise RuntimeError(
            f"unknown rom_key {rom_key!r}; known keys: {sorted(ROM_REGISTRY)}"
        )
    config = load_config()
    rom_dir_str = config.get("rom", {}).get("dir")
    if not rom_dir_str:
        raise RuntimeError(
            "rom.dir not configured in config.yaml; ROM-keyed test harness "
            f"cannot resolve {rom_key!r}"
        )
    rom_path = Path(rom_dir_str) / ROM_REGISTRY[rom_key]
    if not rom_path.exists():
        raise RuntimeError(
            f"ROM file not found for rom_key={rom_key!r}: expected "
            f"{rom_path} (filename {ROM_REGISTRY[rom_key]!r} under "
            f"rom.dir={rom_dir_str!r})"
        )
    return rom_path


def resolve_ra_paths(rom_key: str) -> tuple[Path, Path, Path]:
    """Resolve (retroarch_exe, ra_core_path, rom_path) for a given rom_key.

    Hard-fails if config.yaml is missing any of: emulator.retroarch_path,
    emulator.ra_core_path, or if either path does not exist on disk.
    Propagates `resolve_rom_path` failures.
    """
    config = load_config()
    emu = config.get("emulator", {})
    exe_str = emu.get("retroarch_path")
    core_str = emu.get("ra_core_path")
    if not exe_str:
        raise RuntimeError("emulator.retroarch_path not configured in config.yaml")
    if not core_str:
        raise RuntimeError("emulator.ra_core_path not configured in config.yaml")
    exe = Path(exe_str)
    core = Path(core_str)
    if not exe.exists():
        raise RuntimeError(f"retroarch_path does not exist on disk: {exe}")
    if not core.exists():
        raise RuntimeError(f"ra_core_path does not exist on disk: {core}")
    rom_path = resolve_rom_path(rom_key)
    return exe, core, rom_path
