"""Pytest fixtures for RetroArch headless integration tests.

Fixtures:
    run_scenario       — function-scoped: sends poke scenario via RA harness (RA path)
    fake_dashboard_server — session-scoped: FastAPI dashboard with FakeEmuBackend, no emulator
    fake_game_loaded   — session-scoped: seeds a game into fake_dashboard_server
    replay_ra_dashboard — session-scoped: dashboard wired to a Love Yourself RA session

Diagnostics:
    On emulator/integration test failure, a diagnostic block is appended to the
    pytest longrepr showing dashboard state, DB row counts, and recent log lines.
    Controlled by the ``pytest_runtest_makereport`` hook below.
"""
from __future__ import annotations

import asyncio
import json
import logging
import os
import socket
import subprocess
import tempfile
import threading
from pathlib import Path

import pytest
import pytest_asyncio
import requests as http_requests
import uvicorn
import yaml
from tests.integration.poke_parser import parse_poke_file
from tests.integration.ra_harness import RAHarness, RAHarnessLaunchError

# Resolve project paths
PROJECT_ROOT = Path(__file__).resolve().parents[2]
SCENARIO_DIR = Path(__file__).resolve().parent / "scenarios"

pytestmark = pytest.mark.emulator

LOVE_YOURSELF_ROM_NAME = "Love Yourself.smc"
LOVE_YOURSELF_GAME_ID = "bd94dbb29012c7f5"

TOOTHPASTE_ROM_NAME = "Toothpaste.smc"
CLEAN_SMW_ROM_NAME = "_clean.smc"

# ---------------------------------------------------------------------------
# ROM registry: rom_key -> filename in config.yaml's rom.dir.
#
# Each entry produces one cached session-scoped RAHarness in
# `ra_harness_factory`. Tests must declare which ROM they need via the
# matching named fixture (e.g. `ra_harness_vanilla_smw`); there is no
# implicit `default` fallback any more.
#
# Adding a new ROM requires THREE things:
#   1. A `<rom_key>: "<rom_filename>"` line below.
#   2. A fresh-boot savestate at tests/integration/states/<rom_basename>.state,
#      generated via `python scripts/make_fresh_boot_state.py --rom-key <key>`.
#      Without it, RAPokeEngine can't reset between scenarios and tests share
#      ROM CPU/SPC state across runs (project_transition_state_leak).
#   3. A `ra_harness_<rom_key>` fixture below that calls
#      `ra_harness_factory("<key>")`. Tests reference fixtures by name.
ROM_REGISTRY: dict[str, str] = {
    "vanilla_smw": CLEAN_SMW_ROM_NAME,
    "love_yourself": LOVE_YOURSELF_ROM_NAME,
    "toothpaste": TOOTHPASTE_ROM_NAME,
}

# Per-ROM "fresh boot" savestate. Generated by ``scripts/make_fresh_boot_state.py``
# and committed under tests/integration/states/. Loaded by RAPokeEngine before
# every scenario so the harness, which is session-scoped per rom_key, doesn't
# leak SPC700/CPU state between transition scenarios. See
# docs/superpowers/plans/2026-05-14-transition-state-leak-followup.md.
INTEGRATION_STATES_DIR = Path(__file__).resolve().parent / "states"


def _state_path_for(rom_filename: str) -> Path | None:
    """Resolve the fresh-boot savestate for ``rom_filename`` if one is committed.

    Returns ``None`` when no .state file exists for the ROM yet — the harness
    treats this as "skip the per-scenario boot reset". This is the migration
    runway: a new ROM works at session-scope until someone runs
    ``make_fresh_boot_state.py`` for it, then automatically gets per-scenario
    isolation on the next test run.
    """
    candidate = INTEGRATION_STATES_DIR / f"{Path(rom_filename).stem}.state"
    return candidate if candidate.exists() else None


def _resolve_rom_path(rom_key: str) -> Path:
    """Resolve a registered rom_key to an absolute Path under config.yaml's rom.dir.

    Hard-fail on every step:
      - unknown rom_key (registry typo)
      - rom.dir missing from config.yaml
      - rom.dir set but the registered filename isn't present on disk

    Hard-fail (RuntimeError) rather than pytest.skip so missing infrastructure
    surfaces as a red test per CLAUDE.md ("an env var the harness needs - is
    a failure, not a skip").
    """
    if rom_key not in ROM_REGISTRY:
        raise RuntimeError(
            f"unknown rom_key {rom_key!r}; known keys: {sorted(ROM_REGISTRY)}"
        )
    config = _load_config()
    rom_dir_str = config.get("rom", {}).get("dir")
    if not rom_dir_str:
        raise RuntimeError(
            "rom.dir not configured in config.yaml; ROM-keyed test harness "
            f"cannot resolve {rom_key!r}"
        )
    rom_path = Path(rom_dir_str) / ROM_REGISTRY[rom_key]
    if not rom_path.exists():
        raise RuntimeError(
            f"ROM file not found for rom_key={rom_key!r}: expected "
            f"{rom_path} (filename {ROM_REGISTRY[rom_key]!r} under "
            f"rom.dir={rom_dir_str!r})"
        )
    return rom_path


def _resolve_ra_paths(rom_key: str) -> tuple[Path, Path, Path]:
    """Resolve (retroarch_exe, ra_core_path, rom_path) for a given rom_key.

    Hard-fail if any of:
      - emulator.retroarch_path missing/empty in config.yaml
      - emulator.ra_core_path missing/empty in config.yaml
      - retroarch_path file does not exist on disk
      - ra_core_path file does not exist on disk
      - rom_path can't be resolved by `_resolve_rom_path` (propagates)
    """
    config = _load_config()
    emu = config.get("emulator", {})
    exe_str = emu.get("retroarch_path")
    core_str = emu.get("ra_core_path")
    if not exe_str:
        raise RuntimeError(
            "emulator.retroarch_path not configured in config.yaml"
        )
    if not core_str:
        raise RuntimeError(
            "emulator.ra_core_path not configured in config.yaml"
        )
    exe = Path(exe_str)
    core = Path(core_str)
    if not exe.exists():
        raise RuntimeError(f"retroarch_path does not exist on disk: {exe}")
    if not core.exists():
        raise RuntimeError(f"ra_core_path does not exist on disk: {core}")
    rom_path = _resolve_rom_path(rom_key)
    return exe, core, rom_path


def _load_config() -> dict:
    """Load config.yaml from project root."""
    config_path = PROJECT_ROOT / "config.yaml"
    if config_path.exists():
        with open(config_path) as f:
            return yaml.safe_load(f)
    return {}


def _free_port() -> int:
    """Find a free TCP port."""
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _free_udp_port() -> int:
    """Find a free UDP port.

    Small TOCTOU window between the bind here releasing and RetroArch binding
    to the same port — acceptable because the harness's NCI ping retries cover
    transient failures, and the loopback UDP port space is otherwise quiet on
    a test host.
    """
    with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as s:
        s.bind(("127.0.0.1", 0))
        return s.getsockname()[1]


def _hard_kill(proc: subprocess.Popen) -> None:
    """Best-effort kill for subprocess processes.

    On Windows, ``Popen.terminate()`` and ``Popen.kill()`` both call
    ``TerminateProcess()`` — there is no real escalation between them.  Use
    ``taskkill /F /T`` so the whole tree dies and we don't leak children.
    Every wait gets a timeout so a wedged process can't hang the pytest
    finalizer.
    """
    if proc.poll() is not None:
        return
    if os.name == "nt":
        subprocess.run(
            ["taskkill", "/F", "/T", "/PID", str(proc.pid)],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
    else:
        proc.terminate()
    try:
        proc.wait(timeout=5)
    except subprocess.TimeoutExpired:
        proc.kill()
        try:
            proc.wait(timeout=2)
        except subprocess.TimeoutExpired:
            pass


# -- Seeded-game fixture for frontend contract smoke tests -------------------
FAKE_GAME_NAME = "FakeGame"


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def fake_dashboard_server():
    """Start a FastAPI dashboard with a FakeEmuBackend — no live emulator required.

    Mirrors the real ``dashboard_server`` fixture but swaps ``session.emu`` for
    the in-process FakeEmuBackend (see tests/conftest.py) so tests can exercise
    the dashboard's HTTP API and SessionManager without booting an emulator.

    The dashboard's background event_loop still runs and keeps trying to open
    a backend connection on the configured port — nothing listens there, so each
    attempt fails fast and the loop sleeps. The session's ``emu`` reference is
    the fake, which ``SystemState`` reads for ``emu_connected``.

    Yields (base_url, db, session).
    """
    from tests.conftest import FakeEmuBackend

    from spinlab.config import AppConfig, EmulatorConfig, NetworkConfig, PracticeConfig
    from spinlab.dashboard import create_app
    from spinlab.db import Database

    tmp = tempfile.mkdtemp(prefix="spinlab_fake_")
    tmp_path = Path(tmp)

    db = Database(str(tmp_path / "spinlab.db"))
    dashboard_port = _free_port()
    # Port is unused — pick a free one so the real event_loop's connect()
    # attempts fail with connection-refused rather than colliding with a
    # running service.
    fake_tcp_port = _free_port()

    config = AppConfig(
        network=NetworkConfig(host="127.0.0.1", port=fake_tcp_port, dashboard_port=dashboard_port),
        emulator=EmulatorConfig(
            savestate_dir=tmp_path / "ra",
            spinlab_state_dir=tmp_path / "sl",
        ),
        data_dir=tmp_path,
        rom_dir=None,
        practice=PracticeConfig(),
    )

    app = create_app(db=db, config=config)
    # Swap the backend for the fake *before* starting uvicorn so the lifespan-started
    # event_loop's real-backend retries don't matter: state reads session.emu.
    fake_emu = FakeEmuBackend(connected=True)
    app.state.session.emu = fake_emu
    app.state.session.capture.emu = fake_emu
    app.state.session.cold_fill.emu = fake_emu

    uvi_config = uvicorn.Config(app, host="127.0.0.1", port=dashboard_port, log_level="warning")
    server = uvicorn.Server(uvi_config)

    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    base_url = f"http://127.0.0.1:{dashboard_port}"
    for _ in range(40):
        try:
            resp = http_requests.get(f"{base_url}/api/state", timeout=1)
            if resp.status_code == 200:
                break
        except http_requests.ConnectionError:
            pass
        await asyncio.sleep(0.25)
    else:
        pytest.fail("Fake dashboard server did not start within 10 seconds")

    yield base_url, db, app.state.session

    server.should_exit = True
    thread.join(timeout=5)
    db.close()
    import shutil
    shutil.rmtree(tmp, ignore_errors=True)


@pytest_asyncio.fixture(scope="session", loop_scope="session")
async def fake_game_loaded(fake_dashboard_server):
    """Seed a minimal game + segments + reference + attempts + session, then
    drive the real ``switch_game`` path so SystemState reports a loaded game.

    Uses ``fake_dashboard_server`` (no live emulator) so frontend contract tests have
    stable data on every tab without the emulator marker.

    Session-scoped to match ``fake_dashboard_server``'s session loop — seeding
    is one-time and ``switch_game`` must run on the session loop so any
    asyncio primitives it creates stay bound to it.

    Yields the seeded game_id.
    """
    from tests.factories import seed_basic_game
    _base_url, db, session = fake_dashboard_server
    game_id = seed_basic_game(db)
    # switch_game is the real code path used by _handle_rom_info /
    # _handle_game_context; emu_connected is already True via FakeEmuBackend.
    await session.switch_game(game_id, FAKE_GAME_NAME)
    yield game_id


# ---------------------------------------------------------------------------
# RetroArch poke harness
# ---------------------------------------------------------------------------


class _HarnessFactory:
    """Session-scoped cache mapping rom_key -> RAHarness.

    Separated from the pytest fixture so unit tests can drive the cache and
    teardown logic without a real fixture lifecycle.
    """

    def __init__(self) -> None:
        self._cache: dict[tuple[str, bool], RAHarness] = {}

    def __call__(self, rom_key: str, use_fresh_state: bool = True) -> RAHarness:
        """Return (or create + cache) a harness for ``rom_key``.

        ``use_fresh_state=True`` (the default) wires a per-launch isolated
        savestate_directory with the fresh-boot state from
        tests/integration/states/ pre-staged at FRESH_BOOT_STATE_SLOT, and
        causes RAPokeEngine to LOAD_STATE_SLOT it before each scenario.
        Required by the poke-transition tests to keep SPC700/CPU state from
        leaking between scenarios.

        ``use_fresh_state=False`` is for fixtures whose RA process must talk
        to the user's actual savestate_directory — currently just the replay
        fixture (its .replay file lives in the user's savestate dir).
        """
        cache_key = (rom_key, use_fresh_state)
        if cache_key in self._cache:
            return self._cache[cache_key]
        retroarch_exe, ra_core_path, rom_path = _resolve_ra_paths(rom_key)
        fresh_state_path = _state_path_for(ROM_REGISTRY[rom_key]) if use_fresh_state else None
        try:
            harness = RAHarness.launch(
                rom_path=rom_path,
                core_path=ra_core_path,
                retroarch_exe=retroarch_exe,
                nci_port=_free_udp_port(),
                fresh_state_path=fresh_state_path,
            )
        except RAHarnessLaunchError as exc:
            # CLAUDE.md: launch failure is a FAILURE, not a skip. RAHarnessLaunchError
            # subclasses RuntimeError so the hard-fail rule still holds; re-raise the
            # typed exception so the diagnostic hook can read its structured fields
            # (pid, port, stage, log_path). Annotate args with rom_key so the test
            # report still names the harness that failed.
            exc.args = (f"ra_harness launch failed for rom_key={rom_key!r}: {exc.args[0]}",)
            raise
        self._cache[cache_key] = harness
        return harness

    def teardown_all(self) -> None:
        while self._cache:
            cache_key, harness = self._cache.popitem()
            try:
                harness.teardown()
            except Exception:
                # Best-effort: surface in the log, don't mask the original test failure.
                logging.getLogger(__name__).exception("ra_harness teardown failed for %r", cache_key)


def _harness_factory_impl() -> _HarnessFactory:
    """Factory constructor surface used by both the pytest fixture and unit tests."""
    return _HarnessFactory()


@pytest.fixture(scope="session")
def ra_harness_factory():
    """Session-scoped factory: factory(rom_key) -> RAHarness, cached per rom_key.

    Hard-fails (RuntimeError) on any missing infrastructure — no pytest.skip.
    See ROM_REGISTRY for the available rom_keys.
    """
    factory = _harness_factory_impl()
    yield factory
    factory.teardown_all()


@pytest.fixture(scope="session")
def ra_harness_vanilla_smw(ra_harness_factory):
    """Session-scoped RAHarness pinned to vanilla SMW (_clean.smc).

    Used by the practice smoke and harness isolation tests. NOT currently
    used by poke transition tests — the committed _clean.state savestate
    lands on the title screen (the no-input free-run settle can't reach
    an in-game frame without controller input injection, which NCI doesn't
    expose). Once make_fresh_boot_state.py learns to drive controller input
    to reach an in-game frame, run_scenario can switch to this harness and
    test vanilla SMW level numbering directly.
    """
    return ra_harness_factory("vanilla_smw")


@pytest.fixture(scope="session")
def ra_harness_love_yourself(ra_harness_factory):
    """Session-scoped RAHarness for Love Yourself.smc, with per-scenario fresh-boot
    reset. Backs ``run_scenario`` for poke transition tests.

    The fresh-boot savestate is in-game (Love Yourself's intro lands the
    player in a level on its own; no controller input needed), so SPC700/CPU
    state can't leak between scenarios. This is the harness that resolved
    project_transition_state_leak.
    """
    return ra_harness_factory("love_yourself")


@pytest.fixture(scope="session")
def ra_harness_love_yourself_no_reset(ra_harness_factory):
    """Session-scoped RAHarness for Love Yourself.smc, WITHOUT fresh-boot reset.

    The only consumer is the replay fixture, which needs RA's
    ``savestate_directory`` to be the user's actual savestate dir so RA can
    find the staged ``.replay`` files. The fresh-state harness override
    isolates ``savestate_directory`` to a tmp dir, which would hide the
    .replay files from RA. Distinct cache key from ``ra_harness_love_yourself``,
    so a second RA process is launched for this purpose.
    """
    return ra_harness_factory("love_yourself", use_fresh_state=False)


@pytest.fixture
def run_scenario(ra_harness_love_yourself):
    """Send a poke scenario through the Love Yourself RA harness and collect events.

    Pinned to Love Yourself because that's the ROM whose committed fresh-boot
    savestate lands the player in a level (vanilla SMW's lands on the title
    screen — see ra_harness_vanilla_smw). The detector tests are ROM-agnostic
    in practice: they assert on transitions in tracked ADDR_MAP bytes, which
    the engine zeros after the savestate load — so absolute level numbers
    don't matter, only that the ROM isn't actively overwriting our pokes.
    """

    async def _run(scenario_name: str, timeout: float = 30.0) -> list:
        scenario_path = SCENARIO_DIR / scenario_name
        if not scenario_path.exists():
            pytest.fail(f"Scenario file not found: {scenario_path}")
        scenario = parse_poke_file(str(scenario_path))
        return await asyncio.wait_for(
            asyncio.to_thread(ra_harness_love_yourself.engine.run_scenario, scenario),
            timeout=timeout,
        )

    return _run


@pytest.fixture(scope="session")
def replay_ra_dashboard(ra_harness_love_yourself_no_reset):
    """Start a dashboard pointed at the Love Yourself RA session for replay tests.

    Mirrors ``replay_dashboard`` but uses the RA backend (build_orchestrator)
    instead of the legacy Mesen+TCP backend.  The RA process is already up (ra_harness_love_yourself);
    this fixture wires the dashboard to it via NCI at the configured port.

    Phase E PLAY_REPLAY requires RA to be in PLAYING (not PAUSED) state.
    The harness leaves RA paused; we unpause it here so the orchestrator's
    _on_replay → MoviePlayer.play → play_replay() works correctly.

    Yields (base_url, db, tmp_path) — tmp_path is the data dir where the
    test should stage its fixture files.
    """
    from spinlab.config import AppConfig, EmulatorConfig, NetworkConfig, PracticeConfig
    from spinlab.dashboard import create_app
    from spinlab.db import Database

    config_raw = _load_config()
    emu_raw = config_raw.get("emulator", {})

    # Resolve savestate_dir from config — required by build_orchestrator.
    savestate_dir_str = emu_raw.get("savestate_dir")
    ra_core_subdir = emu_raw.get("ra_core_subdir") or "Snes9x"

    if not savestate_dir_str:
        pytest.skip("replay_ra_dashboard: emulator.savestate_dir not configured")

    savestate_dir = Path(savestate_dir_str)

    tmp = tempfile.mkdtemp(prefix="spinlab_ra_replay_")
    tmp_path = Path(tmp)
    spinlab_state_dir = tmp_path / "spinlab_states"
    spinlab_state_dir.mkdir(parents=True, exist_ok=True)

    db = Database(str(tmp_path / "spinlab.db"))
    dashboard_port = _free_port()

    rom_dir = _resolve_rom_path("love_yourself").parent

    config = AppConfig(
        network=NetworkConfig(
            host="127.0.0.1",
            port=15482,  # unused — RA backend uses NCI, not TCP
            dashboard_port=dashboard_port,
            # Talk to the harness's RA, not whatever the user's config.yaml
            # advertises. The harness picks a free port per session.
            nci_port=ra_harness_love_yourself_no_reset.client.port,
        ),
        emulator=EmulatorConfig(
            savestate_dir=savestate_dir,
            spinlab_state_dir=spinlab_state_dir,
            ra_core_subdir=ra_core_subdir,
        ),
        data_dir=tmp_path,
        rom_dir=rom_dir,
        practice=PracticeConfig(),
    )

    app = create_app(db=db, config=config)

    uvi_config = uvicorn.Config(app, host="127.0.0.1", port=dashboard_port, log_level="warning")
    server = uvicorn.Server(uvi_config)

    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()

    base_url = f"http://127.0.0.1:{dashboard_port}"

    import time as _time

    # Wait for uvicorn to come up.
    for _ in range(40):
        try:
            resp = http_requests.get(f"{base_url}/api/state", timeout=1)
            if resp.status_code == 200:
                break
        except http_requests.ConnectionError:
            pass
        _time.sleep(0.25)
    else:
        server.should_exit = True
        thread.join(timeout=5)
        db.close()
        import shutil as _s
        _s.rmtree(tmp, ignore_errors=True)
        pytest.fail("replay_ra_dashboard: uvicorn did not start within 10 seconds")

    # Wait for the orchestrator to connect to RA and receive rom_info so the
    # dashboard has a game_id (required before /api/replay/start will resolve).
    for _ in range(40):
        resp = http_requests.get(f"{base_url}/api/state", timeout=2)
        state = resp.json()
        if state.get("emu_connected") and state.get("game_id"):
            break
        _time.sleep(0.25)
    else:
        server.should_exit = True
        thread.join(timeout=5)
        db.close()
        import shutil as _s
        _s.rmtree(tmp, ignore_errors=True)
        pytest.fail("replay_ra_dashboard: orchestrator did not connect to RA within 10 seconds")

    # PLAY_REPLAY requires RA to be in PLAYING state. The harness left RA paused;
    # unpause it now so the orchestrator's _on_replay → MoviePlayer.play_replay()
    # actually starts playback. Use the harness's NCI client directly.
    harness = ra_harness_love_yourself_no_reset
    try:
        status = harness.client.get_status()
        if status.state == "PAUSED":
            harness.client.pause_toggle()
            _time.sleep(0.3)  # allow RA to settle into PLAYING before the test POSTs replay/start
    except Exception as exc:
        # Tear down what we built before failing — preserves the no-yield
        # invariant for downstream cleanup hooks.
        server.should_exit = True
        thread.join(timeout=5)
        db.close()
        import shutil as _s
        _s.rmtree(tmp, ignore_errors=True)
        pytest.fail(_format_pause_toggle_failure(harness, exc))

    yield base_url, db, tmp_path

    server.should_exit = True
    thread.join(timeout=5)
    db.close()
    import shutil as _shutil_cleanup
    _shutil_cleanup.rmtree(tmp, ignore_errors=True)


# ---------------------------------------------------------------------------
# Diagnostic dump on integration test failure
# ---------------------------------------------------------------------------

# Collect event log lines from the spinlab logger during the entire session.
# The handler is installed once at import time; the ring buffer is read by
# the failure hook to include recent events in the pytest report.

_EVENT_LOG_CAPACITY = 200


class _RingHandler(logging.Handler):
    """Fixed-capacity ring buffer logging handler."""

    def __init__(self, capacity: int = _EVENT_LOG_CAPACITY):
        super().__init__()
        self._buf: list[str] = []
        self._capacity = capacity

    def emit(self, record: logging.LogRecord) -> None:
        line = self.format(record)
        self._buf.append(line)
        if len(self._buf) > self._capacity:
            self._buf = self._buf[-self._capacity:]

    def recent(self, n: int = 30) -> list[str]:
        return self._buf[-n:]

    def clear(self) -> None:
        self._buf = []


_ring = _RingHandler()
_ring.setFormatter(logging.Formatter("%(asctime)s %(name)s %(levelname)s %(message)s"))
logging.getLogger("spinlab").addHandler(_ring)


def _format_pause_toggle_failure(harness, exc: Exception) -> str:
    """Format a pause_toggle failure message for the replay fixture path.

    Pulls pid/port off the harness defensively (older test doubles may not
    have them) and includes the original exception type + message.
    """
    try:
        pid = harness.proc.pid
    except Exception:
        pid = "<unknown>"
    try:
        port = harness.client.port
    except Exception:
        port = "<unknown>"
    return (
        f"replay_ra_dashboard: pause_toggle on harness "
        f"(pid={pid}, port={port}) failed with {type(exc).__name__}: {exc}"
    )


# How many lines to tail from each diagnostic source. 30 is plenty to capture the
# RA boot sequence (~10 lines) plus any "core failed to load" + crash spew that
# follows, without burying the pytest report under thousands of frame-tick lines.
_HARNESS_LOG_TAIL_LINES = 30
_RING_TAIL_LINES = 30


def _collect_diagnostics(item: pytest.Item) -> str:
    """Best-effort snapshot of integration test state at failure time.

    Walks ``item.funcargs`` and:
      - For tuples shaped ``(str_url, Database, ...)``, emits an /api/state +
        DB-counts block (matches the dashboard-fixture shape).
      - For objects exposing ``.proc`` (a Popen) and ``.client`` (NCIClient),
        emits a harness block with pid / port / proc.poll() and the last
        ``_HARNESS_LOG_TAIL_LINES`` of the per-launch retroarch.log if available.

    Always tails the in-process spinlab log ring buffer at the end.
    """
    parts: list[str] = []

    for fixture_name, fixture_val in item.funcargs.items():
        # ---- Dashboard-shaped: (base_url, db, _) ----
        if (
            isinstance(fixture_val, tuple)
            and len(fixture_val) >= 2
            and isinstance(fixture_val[0], str)
            and fixture_val[0].startswith("http")
        ):
            base_url = fixture_val[0]
            db = fixture_val[1]
            parts.append(f"  fixture: {fixture_name}")
            try:
                state = http_requests.get(f"{base_url}/api/state", timeout=2).json()
                parts.append(f"  /api/state: {json.dumps(state, indent=2)}")
            except Exception as exc:
                parts.append(f"  /api/state: <unavailable: {exc}>")
            try:
                seg_count = db.conn.execute(
                    "SELECT COUNT(*) FROM segments WHERE active = 1"
                ).fetchone()[0]
                ref_count = db.conn.execute(
                    "SELECT COUNT(*) FROM capture_runs"
                ).fetchone()[0]
                draft_count = db.conn.execute(
                    "SELECT COUNT(*) FROM capture_runs WHERE draft = 1"
                ).fetchone()[0]
                parts.append(
                    f"  DB: {seg_count} active segments, "
                    f"{ref_count} capture_runs ({draft_count} drafts)"
                )
            except Exception as exc:
                parts.append(f"  DB: <unavailable: {exc}>")
            continue

        # ---- Harness-shaped: duck-types on .proc + .client ----
        if hasattr(fixture_val, "proc") and hasattr(fixture_val, "client"):
            try:
                proc_status = fixture_val.proc.poll()
            except Exception as exc:
                proc_status = f"<poll failed: {exc}>"
            try:
                port = fixture_val.client.port
            except Exception:
                port = "<unknown>"
            try:
                pid = fixture_val.proc.pid
            except Exception:
                pid = "<unknown>"
            parts.append(
                f"  harness: {fixture_name} pid={pid} port={port} proc.poll()={proc_status}"
            )
            log_path = getattr(fixture_val, "log_path", None)
            if log_path is not None:
                try:
                    if log_path.exists():
                        text = log_path.read_text(errors="replace")
                        tail = text.splitlines()[-_HARNESS_LOG_TAIL_LINES:]
                        if tail:
                            parts.append(f"  retroarch.log tail ({len(tail)} lines):")
                            for line in tail:
                                parts.append(f"    {line}")
                except Exception as exc:
                    parts.append(f"  retroarch.log: <unavailable: {exc}>")

    # --- Recent event log (always include if anything in the ring) ---
    recent = _ring.recent(_RING_TAIL_LINES)
    if recent:
        parts.append(f"  Recent spinlab log ({len(recent)} lines):")
        for line in recent:
            parts.append(f"    {line}")

    if not parts:
        return ""
    return "\n--- SpinLab Integration Diagnostics ---\n" + "\n".join(parts)


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    """Append diagnostic state to the report when an integration test fails."""
    outcome = yield
    report = outcome.get_result()
    if report.when != "call" or not report.failed:
        return
    # Only for tests in the integration directory
    if "integration" not in str(item.fspath):
        return
    diag = _collect_diagnostics(item)
    if diag:
        # `longreprtext` is a read-only property in current pytest, so the
        # diagnostic block has to ride along on `sections` instead.  pytest
        # renders sections in the terminal report after the traceback.
        report.sections.append(("SpinLab Diagnostics", diag))


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_setup(item):
    """Clear the diagnostic ring buffer at the start of each integration test
    so the failure diagnostic only shows logs from the current test, not stale
    lines bled in from earlier tests in the session-scoped harness."""
    if "integration" in str(item.fspath):
        _ring.clear()
    yield
